pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

include ':FtcRobotController'
include ':TeamCode'
dependencyResolutionManagement {
    versionCatalogs {
        build {
            from files('gradle/build.versions.toml')
        }
    }
}
